# fly.toml app configuration file generated for blog-odoom-net on 2023-11-30T20:36:03-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = "blog-odoom-net"
primary_region = "iad"

[build]
  image = "ghost:5.74.5"

[http_service]
  internal_port = 2368
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[env]  
  url = "https://blog-odoom-net.fly.dev"  
  database__client = "sqlite3"  
  database__connection__filename = "content/data/ghost-blog-odoom-net.db"  
  database__useNullAsDefault = "true"  
  database__debug = "false"
  
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source="data"
  destination="/var/lib/ghost/content"

