baseURL = "https://blog.odoom.net/"
disablePathToLower = true
languageCode = "en-us"
title = "Musings"
theme = "paper"

[params]
  color = "linen"
  description = "Technical and untechnical musings"
  favicon = "favicon.svg"

[outputs]
  home = ["HTML", "RSS"]

[security]
  [security.funcs]
    getenv = ['^HUGO_', '^CI', '^NIX_STORE_PATH$']

[markup]
  [markup.highlight]
    style = "monokailight"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
